### ISSUE TITLE
option to coerce find_item to data.frame

### ISSUE THREAD

**Issue by pssguy** [Ironholds/WikidataR#12]
This would be useful
Or explanation of how to  do it. Specifically interested in id and label

**Comment by Ironholds** [comment]
Good idea. I'll look into it.

**Comment by Ironholds** [comment]
So it looks like this would be pretty difficult to do in a scaleable way since there are parameters that simply aren't returned if an article lacks them. See, for example, <code>t <- find_item("foo", language = "en", limit = 10)</code>. Elements 2 and 3 have 9 entries; the rest 8. Turning these into a data frame would be preeetty manual and mungy. A list is probably a better representation precisely because it has variable numbers of entries.
