### ISSUE TITLE
Some geo queries failing

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/WikidataR#28]
CC @serenasignorelli and @bearloga - queries like the following are producing 500 requests:

```
 sf_locations <- get_geo_entity("Q62")
```

Did something change at the SPARQL endpoint?

**Comment by bearloga** [comment]
Ran the query in https://query.wikidata.org and got:

"java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: there can be only one "run last" join in any group"

![screen shot 2017-09-19 at 10 31 03 am](https://user-images.githubusercontent.com/1807519/30606209-c45b62c2-9d25-11e7-9db8-b1982ec65aae.png)

The problem is actually with the query. There are two `SERVICE wikibase:label` statements that collide. I'll make a PR right now. **Update**: #29
